version: '3.9'
services:

  db:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - ./mount:/var/lib/postgresql/data:rw
      - ./my_scripts:/root/src:ro
    networks:
      - db-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - db-network

networks:
  db-network: